# Generated by Django 4.2.4 on 2023-08-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subjectvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitoDNAMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(decimal_places=3, default=None, max_digits=15, null=True)),
                ('source', models.CharField(choices=[('pl', 'plasma'), ('ur', 'urine')], max_length=2)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjectvisit')),
            ],
        ),
    ]
